# Clustering Configuration for Conversation Analysis
# This configuration file contains parameters for HDBSCAN-based clustering
# and temporal-semantic analysis of conversations.

# HDBSCAN Configuration
hdbscan:
  min_cluster_size: 2      # Keep at 2 to capture small conversations
  min_samples: 1           # Reduced to be more flexible in cluster formation
  cluster_selection_epsilon: 0.35  # Adjusted for balance between cohesion and number of clusters
  metric: 'precomputed'    # Use pre-computed similarity matrix

# Time-based Weighting
time_weighting:
  enabled: true
  time_weight: 0.4         # Increased to give more weight to temporal proximity
  decay_factor: 0.8
  similarity_threshold: 0.6  # Increased to create more distinct conversations

# Text Processing
text_processing:
  min_df: 1              # Keep at 1 for rare terms
  max_df: 0.95           # Adjusted for better term coverage
  ngram_range: [1, 2]

# Vector Processing Parameters
# Controls how message vectors are processed before clustering
vectors:
  normalize: true         # Keep vectors normalized
  use_idf: true          # Use IDF weighting

# Cluster Refinement
refinement:
  reassignment_threshold: 0.55  # More strict to avoid incorrect groupings
  max_outlier_ratio: 0.25    # Reduced to force more groupings

# Performance Optimization
# Parameters for optimizing clustering performance
optimization:
  use_gpu: false         # Whether to use GPU acceleration if available
  batch_size: 1000       # Batch size for processing large datasets
  cache_similarity: true # Cache similarity matrix for repeated operations 