# Clustering Configuration for Conversation Analysis
# This configuration file contains parameters for HDBSCAN-based clustering
# and temporal-semantic analysis of conversations.

# HDBSCAN Parameters
# These parameters control the density-based clustering algorithm
hdbscan:
  min_cluster_size: 2      # Mantener en 2 para capturar conversaciones pequeñas
  min_samples: 1           # Reducido para ser más flexible en la formación de clusters
  cluster_selection_epsilon: 0.35  # Ajustado para balance entre cohesión y número de clusters
  metric: 'precomputed'    # Use pre-computed similarity matrix

# Temporal-Semantic Weighting Parameters
# Controls how time and content similarity are balanced
temporal:
  time_weight: 0.4         # Aumentado para dar más peso a la proximidad temporal
  max_time_gap: 3600      # Reducido a 1 hora para separar mejor las conversaciones
  similarity_threshold: 0.6  # Aumentado para crear conversaciones más distintas

# Vector Processing Parameters
# Controls how message vectors are processed before clustering
vectors:
  normalize: true         # Keep vectors normalized
  use_idf: true          # Use IDF weighting
  min_df: 1              # Mantener en 1 para términos raros
  max_df: 0.95           # Ajustado para mejor cobertura de términos

# Outlier Handling Parameters
# Controls how messages that don't fit well into clusters are handled
outliers:
  reassignment_threshold: 0.55  # Más estricto para evitar agrupaciones incorrectas
  max_outlier_ratio: 0.25    # Reducido para forzar más agrupaciones

# Performance Optimization
# Parameters for optimizing clustering performance
optimization:
  use_gpu: false         # Whether to use GPU acceleration if available
  batch_size: 1000       # Batch size for processing large datasets
  cache_similarity: true # Cache similarity matrix for repeated operations 